### ISSUE TITLE
wrong links on http://dev.office.com/code-samples-detail/5792 

### ISSUE THREAD

**Issue by ShuanWang** [OfficeDev/Outlook-Add-in-JavaScript-ValidateIdentityToken#2]
all source code links on http://dev.office.com/code-samples-detail/5792 are wrong, e.g.  AuthClaimTypes.cs and IdentityToken.xml.  They are causing 404 now.  They should point to Github files.  Please fix them.

**Comment by DianeD** [comment]
Links were fixed but didn't close this issue. Thanks for reporting, @ShuanWang !
