### ISSUE TITLE
Having an error - Access is Denied

### ISSUE THREAD

**Issue by commochum** [OfficeDev/Outlook-Add-in-JavaScript-ValidateIdentityToken#6]
After I click on the add-in, I am getting an error below:

"XMLHttpRequest: Network Error 0x80070005, Access is denied."

Is there something I need to change on the code? I followed the documentation Build and Debug as per this link but still I am getting this error.

I hope to get any feedback on fixing this issue.

![error - outlook-add-in-javascript-validateidentitytoken](https://user-images.githubusercontent.com/42759251/46329806-1e6f5c80-c653-11e8-931e-b7fc9ae5263f.PNG)

**Comment by lindalu-MSFT** [comment]
Hi @commochum Are you still having this issue? I apologize that no one has been tending the issues in this repo. Thanks for taking the time to report it. I'm going to go ahead and close this issue, if you still have problems, try posting your question on StackOverflow.
